### ISSUE TITLE
The latest sklearn doesn't support Python2.7

### ISSUE THREAD

**Issue by 4B5F5F4B** [CheckPointSW/Karta#23]
Scikit-learn 0.20 was the last version to support Python2.7，so I think we'd better to use this version in setup.py like this

```
install_requires=['elementals', 'sark', 'pydocstyle', 'flake8', 'click', 'scikit-learn==0.20.0'],
```

**Comment by echin20** [comment]
Did that actually work for you? I stopped at scipy and said it needed Python >= 3.5

**Comment by 4B5F5F4B** [comment]
> Did that actually work for you? I stopped at scipy and said it needed Python >= 3.5

I installed scikit-learn manually like this:

pip install scikit-learn==0.20.0

**Comment by chkp-eyalit** [comment]
Probably worked for me since I installed it some months ago. Will check your suggested fix.
