### ISSUE TITLE
IOError: [Errno 13] Permission denied even though all file permissions are enabled

### ISSUE THREAD

**Issue by LusKrew** [CheckPointSW/Karta#45]
I was attempting to run an IDA plugin called Karta through Cygwin's CLI and I kept on getting the error message:

Traceback (most recent call last):
  File "karta_analyze_src.py", line 310, in <module>
    main(sys.argv[1:])
  File "karta_analyze_src.py", line 303, in main
    analyzeLibrary(constructConfigPath(library_name, library_version), bin_dirs, archive_paths, prompter)
  File "karta_analyze_src.py", line 106, in analyzeLibrary
    archive_files = list(locateFiles(bin_dir, filter(lambda x: x.endswith("." + bin_suffix), getArchiveFiles(compiled_ar)) if not ignore_archive else None, bin_suffix))
  File "C:\Users\wyin\Documents\Karta-master\src\ar_parser.py", line 10, in getArchiveFiles
    ar_fd = open(ar_path, 'rb')
IOError: [Errno 13] Permission denied: 'C:/Users/wyin/Documents/cryptopp820'

I looked at my file permissions for C:/Users/wyin/Documents/cryptopp820 and i saw that I had every permission already enabled.

What I can I do to resolved this error?

it seems like its trying to open the directory in python and that causes the error

**Comment by chkp-eyalit** [comment]
Sorry for the delay in the response. It looks like there might be a mixup in the CLI arguments that are passed. Could you please list the full command you are using?

My guess is that a directory is passed instead of the path to the archive file, which caused this issue.

**Comment by chkp-eyalit** [comment]
Being inactive, I'm closing this ticket. If there error persists (even when passing the CLI arguments correctly), feel free to re-open this ticket.
