### ISSUE TITLE
A problem on adding support for a new open source

### ISSUE THREAD

**Issue by MageWeiG** [CheckPointSW/Karta#46]
when I use karta_analyze_src.py to add new open source , karta told me that there are not anchor function, how should I do next?

**Comment by chkp-eyalit** [comment]
Hi, sorry for the delayed response.
Could you elaborate on which open source is it? And if possible also which version?

Karta locates the library using anchor functions, and then matches the rest of the functions. If there are no good candidates to serve as anchor functions, Karta won't be able to locate the statically compiled library in a bigger binary. I am afraid that in such cases Karta won't be able to support this open source.

However, if you could share the open source, I will verify this manually, and maybe there will be a way to update Karta to support it.

**Comment by chkp-eyalit** [comment]
Closed due to lack of activity, Missing anchor functions in a target library is a known limitation.
