### ISSUE TITLE
A problem in isAnchor function.

### ISSUE THREAD

**Issue by MageWeiG** [CheckPointSW/Karta#47]
I find a problem in src->config->anchor->isAnchor() when I look at your code.

this function can only run the first branch, because case can only equal to 1.

**Comment by chkp-eyalit** [comment]
```case``` is incremented in the following line: https://github.com/CheckPointSW/Karta/blob/master/src/config/anchor.py#L51

Essentially, this is a for loop that iterates through the different cases, according to predefined priority. There is no bug in this code.
