### ISSUE TITLE
Installation dependency error

### ISSUE THREAD

**Issue by Noam5** [CheckPointSW/Karta#55]
When installing Karta (tag v2.0.0) using ```py -3 setup.py install``` 

I face the following problem:

```
Installed c:\users\user\appdata\local\programs\python\python38\lib\site-packages\karta-2.0.0-py3.8.egg
Processing dependencies for Karta==2.0.0
Searching for sark==2.0
Reading https://pypi.org/simple/sark/
No local packages or working download links found for sark==2.0
error: Could not find suitable distribution for Requirement.parse('sark==2.0')
```

This was solved by editing setup.py file, removing the version from sark dependency

**Comment by chkp-eyalit** [comment]
Hi, sorry about the late reply, I didn't get a notification about this issue.
Anyway, the issue you are reporting was already resolved in ac00dcfa7699bedc5874943181dbbd69c511fd5d (exactly a year ago) and was a side-effect of sark's migration to Python3.

Happy to see you resolved it on your end as well.
